apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - patch-volumes.yml

commonLabels:
  env: prod

commonAnnotations:
  com.thomasvitale.show: "You Choose!"

configMapGenerator:
  - name: band-config
    files:
      - application.yml
    options:
      labels:
        app: band-service

replicas:
  - count: 5
    name: band-service

images:
  - name: band-service
    newName: ghcr.io/thomasvitale/band-service
    newTag: v1
