apiVersion: apps/v1
kind: Deployment
metadata:
  name: band-service
  labels:
    app: band-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: band-service
  template:
    metadata:
      labels:
        app: band-service
    spec:
      containers:
        - name: band-service
          image: ghcr.io/thomasvitale/band-service:v1-demo
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
